type: object
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier representing a specific product.
  name:
    type: string
  description:
    type: string
  dimensions:
    $ref: dimension.yaml
  category:
    $ref: category.yaml
  images:
    $ref: image_list.yaml
  price:
    type: number
  cost:
    type: number