type: object
properties: 
  height:
    type: integer
    description: The height(visota) of the product
    minimum: 1
    maximum: 999
    example: 10
    nullable: true
  width:
    type: integer
    description: The width(shirina) of the product
    minimum: 1
    maximum: 999
    example: 10
    nullable: true
  length:
    type: integer
    description: The length(dlina) of the product
    minimum: 1
    maximum: 999
    example: 10
    nullable: true
description: The dimentions of the product