get:
  tags:
    - Product
  summary: Get a list of products
  description: Get a list of products
  operationId: listProducts
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product_list.yaml
    '404':
      description: Not Found
      content: 
        application/json:
          schema: 
            $ref: ../../components/schemas/Problem.yaml
post: 
  tags: 
    -  Products
  summary: Create new product
  description: Create new product.
  operationId: createProduct
  requestBody: 
    content: 
      application/json:
        schema: 
          $ref: ../../components/schemas/v1/product.yaml    
  responses: 
    '201':
      description: Created
      headers: 
        Location:
          description: Location of a new resource
          schema: 
            type: string
            example: /v1/products/bc2348b6-c14e-48a4-876d-51834b39831a
    '400':
      description: Bad Request
      content: 
        application/json:
          schema: 
            $ref: ../../components/schemas/Problem.yaml

  